### ISSUE TITLE
Generically parse UserEntry field_data in JavaScript

### ISSUE THREAD

**Issue by kb173** [boku-ilen/web-gis#1]
Probably we will request the corresponding `EntryDefinition`, meaning that we need to add a reference to `UserEntry` saying which `EntryDefinition` it is based on (which generally seems smart). Then we'll want to e.g. create an `<image>` HTML element if there's an image URL in the data.

**Comment by MathiasBaumgartinger** [comment]
For clarification: This issue specifically talks about loading the added `UserEntry`s and display them on the map
