### ISSUE TITLE
Allow visualization of form as matrix

### ISSUE THREAD

**Issue by kb173** [boku-ilen/web-gis#17]
Instead of radio-buttons always being sorted vertically, we want to be able to display them as a matrix, similar to [this example](https://i0.wp.com/resources.pollfish.com/wp-content/uploads/2019/10/Screen-Shot-2019-10-15-at-4.27.44-PM.png?resize=840%2C323&ssl=1)

**Comment by MathiasBaumgartinger** [comment]
Commits [1a3b94a](https://github.com/boku-ilen/web-gis/commit/1a3b94a3875c7ed49f8f2217a7b8953ba5161dcb) and [5d98802](https://github.com/boku-ilen/web-gis/commit/5d9880253a2bfdc490d4cbe5ba914bbef0698ec9) implement the input functionality. Proper display on the overview page is yet to be implemented.
