### ISSUE TITLE
Add user interface for adding UserEntries

### ISSUE THREAD

**Issue by kb173** [boku-ilen/web-gis#2]
Click on map -> window similar to admin site opens for users to add a new entry based on the current project's EntryDefinition(s). In the case of multiple EntryDefinitions, a dropdown for selecting one is at the top.

We'll only handle Point geometry for now for simplicity (-> click on map will always be the pre-filled UserEntry geometry).

**Comment by kb173** [comment]
Note: we should validate whether the sent UserEntry actually corresponds to the EntryDefinition, otherwise users could manually send weird data

**Comment by MathiasBaumgartinger** [comment]
436158d implements a first prototype for dynamic reflections with string, boolean and an image (all hardcoded as of now)

**Comment by MathiasBaumgartinger** [comment]
This should be finished with 84a58cc9f2c096f705d810d690ab773ce783dc71.
